stages:
  - push 
  - pull

push to github:
  stage: push
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - echo "Pushed"



pull from github:
  stage: pull
  when: manual
  script:
    - echo "Pulled"
