FROM python:3

#Set the working directory in the flask container
WORKDIR /usr/src/Chirpr-Social-Network
#Copy all the files to WORKDIR
COPY . .

#Install the dependencies
RUN pip3 install --no-cache flask pymongo
RUN sudo apt-get update && sudo apt-get upgrade -y
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN sudo apt-get update && sudo apt-get install mongodb-org -y
RUN sudo systemctl start mongod

#Use port 5001 to run
EXPOSE 5001

#Command to run the server
CMD ["python", "./main.py"]